package cn.bocrist.entity;

import java.sql.Date;

public class Bootuser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOOTUSER.ID
     *
     * @mbg.generated Sun May 26 09:29:21 CST 2019
     */
    private Short id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOOTUSER.BOOTID
     *
     * @mbg.generated Sun May 26 09:29:21 CST 2019
     */
    private Short bootid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOOTUSER.BOOTNAME
     *
     * @mbg.generated Sun May 26 09:29:21 CST 2019
     */
    private String bootname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOOTUSER.BOOTAGE
     *
     * @mbg.generated Sun May 26 09:29:21 CST 2019
     */
    private Short bootage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOOTUSER.BOOTSEX
     *
     * @mbg.generated Sun May 26 09:29:21 CST 2019
     */
    private String bootsex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BOOTUSER.BOOTBIRTHDAY
     *
     * @mbg.generated Sun May 26 09:29:21 CST 2019
     */
    private Date bootbirthday;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOOTUSER.ID
     *
     * @return the value of BOOTUSER.ID
     *
     * @mbg.generated Sun May 26 09:29:21 CST 2019
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOOTUSER.ID
     *
     * @param id the value for BOOTUSER.ID
     *
     * @mbg.generated Sun May 26 09:29:21 CST 2019
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOOTUSER.BOOTID
     *
     * @return the value of BOOTUSER.BOOTID
     *
     * @mbg.generated Sun May 26 09:29:21 CST 2019
     */
    public Short getBootid() {
        return bootid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOOTUSER.BOOTID
     *
     * @param bootid the value for BOOTUSER.BOOTID
     *
     * @mbg.generated Sun May 26 09:29:21 CST 2019
     */
    public void setBootid(Short bootid) {
        this.bootid = bootid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOOTUSER.BOOTNAME
     *
     * @return the value of BOOTUSER.BOOTNAME
     *
     * @mbg.generated Sun May 26 09:29:21 CST 2019
     */
    public String getBootname() {
        return bootname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOOTUSER.BOOTNAME
     *
     * @param bootname the value for BOOTUSER.BOOTNAME
     *
     * @mbg.generated Sun May 26 09:29:21 CST 2019
     */
    public void setBootname(String bootname) {
        this.bootname = bootname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOOTUSER.BOOTAGE
     *
     * @return the value of BOOTUSER.BOOTAGE
     *
     * @mbg.generated Sun May 26 09:29:21 CST 2019
     */
    public Short getBootage() {
        return bootage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOOTUSER.BOOTAGE
     *
     * @param bootage the value for BOOTUSER.BOOTAGE
     *
     * @mbg.generated Sun May 26 09:29:21 CST 2019
     */
    public void setBootage(Short bootage) {
        this.bootage = bootage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOOTUSER.BOOTSEX
     *
     * @return the value of BOOTUSER.BOOTSEX
     *
     * @mbg.generated Sun May 26 09:29:21 CST 2019
     */
    public String getBootsex() {
        return bootsex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOOTUSER.BOOTSEX
     *
     * @param bootsex the value for BOOTUSER.BOOTSEX
     *
     * @mbg.generated Sun May 26 09:29:21 CST 2019
     */
    public void setBootsex(String bootsex) {
        this.bootsex = bootsex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BOOTUSER.BOOTBIRTHDAY
     *
     * @return the value of BOOTUSER.BOOTBIRTHDAY
     *
     * @mbg.generated Sun May 26 09:29:21 CST 2019
     */
    public Date getBootbirthday() {
        return bootbirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BOOTUSER.BOOTBIRTHDAY
     *
     * @param bootbirthday the value for BOOTUSER.BOOTBIRTHDAY
     *
     * @mbg.generated Sun May 26 09:29:21 CST 2019
     */
    public void setBootbirthday(Date bootbirthday) {
        this.bootbirthday = bootbirthday;
    }
}