package cn.bocrist.entity;

import java.sql.Date;
import java.util.ArrayList;
import java.util.List;

public class BootuserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BOOTUSER
     *
     * @mbg.generated Sun May 26 09:29:21 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BOOTUSER
     *
     * @mbg.generated Sun May 26 09:29:21 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table BOOTUSER
     *
     * @mbg.generated Sun May 26 09:29:21 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOTUSER
     *
     * @mbg.generated Sun May 26 09:29:21 CST 2019
     */
    public BootuserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOTUSER
     *
     * @mbg.generated Sun May 26 09:29:21 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOTUSER
     *
     * @mbg.generated Sun May 26 09:29:21 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOTUSER
     *
     * @mbg.generated Sun May 26 09:29:21 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOTUSER
     *
     * @mbg.generated Sun May 26 09:29:21 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOTUSER
     *
     * @mbg.generated Sun May 26 09:29:21 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOTUSER
     *
     * @mbg.generated Sun May 26 09:29:21 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOTUSER
     *
     * @mbg.generated Sun May 26 09:29:21 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOTUSER
     *
     * @mbg.generated Sun May 26 09:29:21 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOTUSER
     *
     * @mbg.generated Sun May 26 09:29:21 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOTUSER
     *
     * @mbg.generated Sun May 26 09:29:21 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table BOOTUSER
     *
     * @mbg.generated Sun May 26 09:29:21 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Short value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Short value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Short value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Short value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Short value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Short value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Short> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Short> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Short value1, Short value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Short value1, Short value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andBootidIsNull() {
            addCriterion("BOOTID is null");
            return (Criteria) this;
        }

        public Criteria andBootidIsNotNull() {
            addCriterion("BOOTID is not null");
            return (Criteria) this;
        }

        public Criteria andBootidEqualTo(Short value) {
            addCriterion("BOOTID =", value, "bootid");
            return (Criteria) this;
        }

        public Criteria andBootidNotEqualTo(Short value) {
            addCriterion("BOOTID <>", value, "bootid");
            return (Criteria) this;
        }

        public Criteria andBootidGreaterThan(Short value) {
            addCriterion("BOOTID >", value, "bootid");
            return (Criteria) this;
        }

        public Criteria andBootidGreaterThanOrEqualTo(Short value) {
            addCriterion("BOOTID >=", value, "bootid");
            return (Criteria) this;
        }

        public Criteria andBootidLessThan(Short value) {
            addCriterion("BOOTID <", value, "bootid");
            return (Criteria) this;
        }

        public Criteria andBootidLessThanOrEqualTo(Short value) {
            addCriterion("BOOTID <=", value, "bootid");
            return (Criteria) this;
        }

        public Criteria andBootidIn(List<Short> values) {
            addCriterion("BOOTID in", values, "bootid");
            return (Criteria) this;
        }

        public Criteria andBootidNotIn(List<Short> values) {
            addCriterion("BOOTID not in", values, "bootid");
            return (Criteria) this;
        }

        public Criteria andBootidBetween(Short value1, Short value2) {
            addCriterion("BOOTID between", value1, value2, "bootid");
            return (Criteria) this;
        }

        public Criteria andBootidNotBetween(Short value1, Short value2) {
            addCriterion("BOOTID not between", value1, value2, "bootid");
            return (Criteria) this;
        }

        public Criteria andBootnameIsNull() {
            addCriterion("BOOTNAME is null");
            return (Criteria) this;
        }

        public Criteria andBootnameIsNotNull() {
            addCriterion("BOOTNAME is not null");
            return (Criteria) this;
        }

        public Criteria andBootnameEqualTo(String value) {
            addCriterion("BOOTNAME =", value, "bootname");
            return (Criteria) this;
        }

        public Criteria andBootnameNotEqualTo(String value) {
            addCriterion("BOOTNAME <>", value, "bootname");
            return (Criteria) this;
        }

        public Criteria andBootnameGreaterThan(String value) {
            addCriterion("BOOTNAME >", value, "bootname");
            return (Criteria) this;
        }

        public Criteria andBootnameGreaterThanOrEqualTo(String value) {
            addCriterion("BOOTNAME >=", value, "bootname");
            return (Criteria) this;
        }

        public Criteria andBootnameLessThan(String value) {
            addCriterion("BOOTNAME <", value, "bootname");
            return (Criteria) this;
        }

        public Criteria andBootnameLessThanOrEqualTo(String value) {
            addCriterion("BOOTNAME <=", value, "bootname");
            return (Criteria) this;
        }

        public Criteria andBootnameLike(String value) {
            addCriterion("BOOTNAME like", value, "bootname");
            return (Criteria) this;
        }

        public Criteria andBootnameNotLike(String value) {
            addCriterion("BOOTNAME not like", value, "bootname");
            return (Criteria) this;
        }

        public Criteria andBootnameIn(List<String> values) {
            addCriterion("BOOTNAME in", values, "bootname");
            return (Criteria) this;
        }

        public Criteria andBootnameNotIn(List<String> values) {
            addCriterion("BOOTNAME not in", values, "bootname");
            return (Criteria) this;
        }

        public Criteria andBootnameBetween(String value1, String value2) {
            addCriterion("BOOTNAME between", value1, value2, "bootname");
            return (Criteria) this;
        }

        public Criteria andBootnameNotBetween(String value1, String value2) {
            addCriterion("BOOTNAME not between", value1, value2, "bootname");
            return (Criteria) this;
        }

        public Criteria andBootageIsNull() {
            addCriterion("BOOTAGE is null");
            return (Criteria) this;
        }

        public Criteria andBootageIsNotNull() {
            addCriterion("BOOTAGE is not null");
            return (Criteria) this;
        }

        public Criteria andBootageEqualTo(Short value) {
            addCriterion("BOOTAGE =", value, "bootage");
            return (Criteria) this;
        }

        public Criteria andBootageNotEqualTo(Short value) {
            addCriterion("BOOTAGE <>", value, "bootage");
            return (Criteria) this;
        }

        public Criteria andBootageGreaterThan(Short value) {
            addCriterion("BOOTAGE >", value, "bootage");
            return (Criteria) this;
        }

        public Criteria andBootageGreaterThanOrEqualTo(Short value) {
            addCriterion("BOOTAGE >=", value, "bootage");
            return (Criteria) this;
        }

        public Criteria andBootageLessThan(Short value) {
            addCriterion("BOOTAGE <", value, "bootage");
            return (Criteria) this;
        }

        public Criteria andBootageLessThanOrEqualTo(Short value) {
            addCriterion("BOOTAGE <=", value, "bootage");
            return (Criteria) this;
        }

        public Criteria andBootageIn(List<Short> values) {
            addCriterion("BOOTAGE in", values, "bootage");
            return (Criteria) this;
        }

        public Criteria andBootageNotIn(List<Short> values) {
            addCriterion("BOOTAGE not in", values, "bootage");
            return (Criteria) this;
        }

        public Criteria andBootageBetween(Short value1, Short value2) {
            addCriterion("BOOTAGE between", value1, value2, "bootage");
            return (Criteria) this;
        }

        public Criteria andBootageNotBetween(Short value1, Short value2) {
            addCriterion("BOOTAGE not between", value1, value2, "bootage");
            return (Criteria) this;
        }

        public Criteria andBootsexIsNull() {
            addCriterion("BOOTSEX is null");
            return (Criteria) this;
        }

        public Criteria andBootsexIsNotNull() {
            addCriterion("BOOTSEX is not null");
            return (Criteria) this;
        }

        public Criteria andBootsexEqualTo(String value) {
            addCriterion("BOOTSEX =", value, "bootsex");
            return (Criteria) this;
        }

        public Criteria andBootsexNotEqualTo(String value) {
            addCriterion("BOOTSEX <>", value, "bootsex");
            return (Criteria) this;
        }

        public Criteria andBootsexGreaterThan(String value) {
            addCriterion("BOOTSEX >", value, "bootsex");
            return (Criteria) this;
        }

        public Criteria andBootsexGreaterThanOrEqualTo(String value) {
            addCriterion("BOOTSEX >=", value, "bootsex");
            return (Criteria) this;
        }

        public Criteria andBootsexLessThan(String value) {
            addCriterion("BOOTSEX <", value, "bootsex");
            return (Criteria) this;
        }

        public Criteria andBootsexLessThanOrEqualTo(String value) {
            addCriterion("BOOTSEX <=", value, "bootsex");
            return (Criteria) this;
        }

        public Criteria andBootsexLike(String value) {
            addCriterion("BOOTSEX like", value, "bootsex");
            return (Criteria) this;
        }

        public Criteria andBootsexNotLike(String value) {
            addCriterion("BOOTSEX not like", value, "bootsex");
            return (Criteria) this;
        }

        public Criteria andBootsexIn(List<String> values) {
            addCriterion("BOOTSEX in", values, "bootsex");
            return (Criteria) this;
        }

        public Criteria andBootsexNotIn(List<String> values) {
            addCriterion("BOOTSEX not in", values, "bootsex");
            return (Criteria) this;
        }

        public Criteria andBootsexBetween(String value1, String value2) {
            addCriterion("BOOTSEX between", value1, value2, "bootsex");
            return (Criteria) this;
        }

        public Criteria andBootsexNotBetween(String value1, String value2) {
            addCriterion("BOOTSEX not between", value1, value2, "bootsex");
            return (Criteria) this;
        }

        public Criteria andBootbirthdayIsNull() {
            addCriterion("BOOTBIRTHDAY is null");
            return (Criteria) this;
        }

        public Criteria andBootbirthdayIsNotNull() {
            addCriterion("BOOTBIRTHDAY is not null");
            return (Criteria) this;
        }

        public Criteria andBootbirthdayEqualTo(Date value) {
            addCriterion("BOOTBIRTHDAY =", value, "bootbirthday");
            return (Criteria) this;
        }

        public Criteria andBootbirthdayNotEqualTo(Date value) {
            addCriterion("BOOTBIRTHDAY <>", value, "bootbirthday");
            return (Criteria) this;
        }

        public Criteria andBootbirthdayGreaterThan(Date value) {
            addCriterion("BOOTBIRTHDAY >", value, "bootbirthday");
            return (Criteria) this;
        }

        public Criteria andBootbirthdayGreaterThanOrEqualTo(Date value) {
            addCriterion("BOOTBIRTHDAY >=", value, "bootbirthday");
            return (Criteria) this;
        }

        public Criteria andBootbirthdayLessThan(Date value) {
            addCriterion("BOOTBIRTHDAY <", value, "bootbirthday");
            return (Criteria) this;
        }

        public Criteria andBootbirthdayLessThanOrEqualTo(Date value) {
            addCriterion("BOOTBIRTHDAY <=", value, "bootbirthday");
            return (Criteria) this;
        }

        public Criteria andBootbirthdayIn(List<Date> values) {
            addCriterion("BOOTBIRTHDAY in", values, "bootbirthday");
            return (Criteria) this;
        }

        public Criteria andBootbirthdayNotIn(List<Date> values) {
            addCriterion("BOOTBIRTHDAY not in", values, "bootbirthday");
            return (Criteria) this;
        }

        public Criteria andBootbirthdayBetween(Date value1, Date value2) {
            addCriterion("BOOTBIRTHDAY between", value1, value2, "bootbirthday");
            return (Criteria) this;
        }

        public Criteria andBootbirthdayNotBetween(Date value1, Date value2) {
            addCriterion("BOOTBIRTHDAY not between", value1, value2, "bootbirthday");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table BOOTUSER
     *
     * @mbg.generated do_not_delete_during_merge Sun May 26 09:29:21 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table BOOTUSER
     *
     * @mbg.generated Sun May 26 09:29:21 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}