package cn.bocrist.dao;

import cn.bocrist.entity.Bootuser;
import cn.bocrist.entity.BootuserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BootuserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOTUSER
     *
     * @mbg.generated Sun May 26 09:29:21 CST 2019
     */
    long countByExample(BootuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOTUSER
     *
     * @mbg.generated Sun May 26 09:29:21 CST 2019
     */
    int deleteByExample(BootuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOTUSER
     *
     * @mbg.generated Sun May 26 09:29:21 CST 2019
     */
    void deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOTUSER
     *
     * @mbg.generated Sun May 26 09:29:21 CST 2019
     */
    int insert(Bootuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOTUSER
     *
     * @mbg.generated Sun May 26 09:29:21 CST 2019
     */
    int insertSelective(Bootuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOTUSER
     *
     * @mbg.generated Sun May 26 09:29:21 CST 2019
     */
    List<Bootuser> selectByExample(String bootname);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOTUSER
     *
     * @mbg.generated Sun May 26 09:29:21 CST 2019
     */
    Bootuser selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOTUSER
     *
     * @mbg.generated Sun May 26 09:29:21 CST 2019
     */
    int updateByExampleSelective(@Param("record") Bootuser record, @Param("example") BootuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOTUSER
     *
     * @mbg.generated Sun May 26 09:29:21 CST 2019
     */
    int updateByExample(@Param("record") Bootuser record, @Param("example") BootuserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOTUSER
     *
     * @mbg.generated Sun May 26 09:29:21 CST 2019
     */
    void updateByPrimaryKeySelective(Bootuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BOOTUSER
     *
     * @mbg.generated Sun May 26 09:29:21 CST 2019
     */
    int updateByPrimaryKey(Bootuser record);
}